version: '3.8'

services:
  kms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./questionnaire.db:/app/questionnaire.db
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 